/* Personal instructions are data, never executable plugins or payment authority. */
(()=>{'use strict';
const host=window.CodePhiWorkshopHost,orch=window.CodePhiWorkshopOrchestrator;if(!host||!orch)return;
const catalog=[
 {id:'markets',name:'Market research widget',match:/stock|ticker|nasdaq|market|dividend|bitcoin/i,instruction:'Build dated market research and comparison charts. Require an authorized quote source; never invent live prices or imply guaranteed returns.'},
 {id:'chemistry',name:'Element research and mechanism diagrams',match:/element|atomic|chem|ruthen|samari|hydrogen|molecule|periodic/i,instruction:'Keep element names, symbols and atomic numbers consistent. Build cited chemistry cards, exact charts and mechanism diagrams. Separate established evidence from proposed theories; label generated illustrations.'},
 {id:'entertainment',name:'Curated Media Star',match:/song|music|movie|video|floyd|entertainment|concert/i,instruction:'Build playable curated media cards using verified supplied links and recording details. Keep creator ownership attached to the verified wallet. StarCoin payouts require the existing authorized ledger earning event; playback alone does not authorize minting.'},
 {id:'engineering',name:'Engineering workbench',match:/engineer|circuit|mechanism|schematic|design|build|robot/i,instruction:'Prefer specifications, constraints, calculations and diagrams for this task. Do not turn a research result into an unsupported working device.'},
 {id:'store',name:'Store and source discovery',match:/shop|store|sale|curat|affiliate|product/i,instruction:'Build source-backed product and story cards. Use provided offer links, clear disclosures and verified ownership. No invented prices or payment capabilities.'}
];
let profile={skills:[],rules:[],report:'No wallet analysis yet.'},scope='',activeToken='',signals=[];
const panel=document.createElement('section');panel.className='workshop-panel';panel.innerHTML='<header class="media-head"><div><span class="eyebrow">PERSONAL WORKSHOP</span><h2>Skills from your Quants</h2><p>Oracle reads your connected wallet’s search and card activity to prepare reusable instructions for future builds.</p></div></header><div class="component-controls"><button class="button primary" id="scanPersonal">Read wallet and build my skills</button><button class="button secondary" id="usePersonal">Build the suggested card</button></div><p id="personalStatus" role="status">Your wallet records stay separate from other users. Skills do not grant account access or move coins.</p><div id="personalCatalog"></div><details><summary>ChatGPT connection</summary><p id="personalSignIn">ChatGPT website sign-in requires Code Phi’s registered OpenAI client. It is not active yet; the connected Cloudflare GPT can build your personal instructions now.</p></details>';
document.querySelector('.workshop-panel[aria-label="Service connections"]').before(panel);
const el=id=>document.getElementById(id);
function identity(){const session=JSON.parse(localStorage.getItem('starquest_session')||'null');const found=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k.startsWith('starquest_ledger_device_v1:'))continue;let v=localStorage.getItem(k);try{v=JSON.parse(v).deviceToken}catch{}if(/^sq_[A-Za-z0-9_-]{32,}$/.test(v||''))found.push({name:k.slice(26),token:v});}const name=String(session?.key||session?.username||'').toLowerCase();const exact=found.find(x=>x.name.toLowerCase()===name);if(exact)return exact;const unique=[...new Map(found.map(x=>[x.token,x])).values()];if(unique.length!==1)throw Error('Open your connected Unified Wallet in this browser first. No account was selected or created.');return unique[0];}
async function keyFor(token){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));return 'codePhi:personal:v1:'+Array.from(new Uint8Array(bytes)).map(x=>x.toString(16).padStart(2,'0')).join('');}
function render(){el('personalCatalog').replaceChildren();for(const s of profile.skills){const card=document.createElement('article');card.className='component-card';const h=document.createElement('h3');h.textContent=s.name;const p=document.createElement('p');p.textContent=s.instruction;const note=document.createElement('p');note.textContent='Evidence: '+(s.evidence||[]).join(', ');const remove=document.createElement('button');remove.className='button secondary';remove.textContent='Remove this skill';remove.onclick=()=>{profile.skills=profile.skills.filter(x=>x.id!==s.id);persist();render();};card.append(h,p,note,remove);el('personalCatalog').append(card);}el('personalStatus').textContent=profile.report;}
function persist(){if(scope)localStorage.setItem(scope,JSON.stringify(profile));}
async function read(path,token){const r=await fetch('https://quanta-phi-ledger.marvaseater.workers.dev'+path,{headers:{authorization:'Bearer '+token},cache:'no-store',signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok||d.ok===false)throw Error(d.error||'Wallet read failed ('+r.status+').');return d;}
async function scan(){const button=el('scanPersonal');button.disabled=true;try{const owner=identity();activeToken=owner.token;scope=await keyFor(owner.token);el('personalStatus').textContent='Reading your authenticated search and card records…';const results=await Promise.allSettled(['/v1/quants/interests','/v1/quants/card-interactions','/v1/quants/history','/v1/quants/star-coins'].map(p=>read(p,owner.token)));const topics=results[0].status==='fulfilled'?results[0].value.topics||[]:[];const events=results[1].status==='fulfilled'?results[1].value.events||[]:[];const searches=results[2].status==='fulfilled'?results[2].value.searches||[]:[];const tokenRecords=results[2].status==='fulfilled'?results[2].value.tokens||[]:[];const attached=tokenRecords.slice(0,100).flatMap(x=>{try{const d=JSON.parse(x.data_json||'{}');return [{text:[d.query,d.title,d.topic,Array.isArray(d.index_terms)?d.index_terms.join(' '):''].filter(Boolean).join(' ').slice(0,500),count:1}];}catch{return [];}}).filter(x=>x.text);const star=results[3].status==='fulfilled'?results[3].value:null;if(!topics.length&&!events.length&&!searches.length)throw Error('No usable search or click records were returned. Nothing was inferred.');signals=[...attached,...topics.map(x=>({text:x.query,count:Math.min(20,Number(x.hits)||1)})),...events.slice(0,150).map(x=>({text:[x.query_text,x.title,x.index_terms].join(' '),count:1}))];const drafts=catalog.map(t=>{const evidence=signals.filter(x=>t.match.test(x.text));return {...t,match:undefined,score:evidence.reduce((n,x)=>n+x.count,0),evidence:evidence.slice(0,5).map(x=>x.text.slice(0,180))};}).filter(x=>x.score>=2).sort((a,b)=>b.score-a.score);
el('personalStatus').textContent='GPT is writing reusable instructions from '+searches.length+' search records and '+events.length+' card interactions…';const result=await orch.request('/ai',{kind:'skills',topic:host.state().query||'Personal workshop',direction:'Write useful personal skills and explain the next card to build. Treat repeated interests as preferences, never identity certainty.',personalContext:{catalog:drafts,topics:topics.slice(0,30),clicks:events.slice(0,30).map(x=>({query:x.query_text,title:x.title,action:x.action})),attachedQuantTopics:attached.slice(0,20).map(x=>x.text),starActivity:star?{creditCount:Array.isArray(star.history)?star.history.length:0,eventKinds:[...new Set((star.history||[]).map(x=>x.kind).filter(Boolean))].slice(0,12)}:null,starActivityAvailable:!!star},inventory:orch.inventory()});profile={skills:(result.skills||drafts).map(s=>({...s,evidence:(drafts.find(d=>d.id===s.id)?.evidence||topics.slice(0,5).map(t=>t.query))})),rules:result.rules||[],report:result.message,suggestion:result.nextBuild,updatedAt:Date.now()};persist();render();}catch(e){el('personalStatus').textContent=e.message;}finally{button.disabled=false;}}
el('scanPersonal').onclick=scan;
el('usePersonal').onclick=()=>{if(!profile.suggestion){el('personalStatus').textContent='Read your wallet first to prepare an evidence-based build suggestion.';return;}document.getElementById('instruction').value=profile.suggestion;orch.run();};
window.CodePhiPersonalSkills=Object.freeze({context:()=>{try{if(identity().token!==activeToken)return {};}catch{return {};}return {skills:profile.skills,rules:profile.rules};},catalog:()=>catalog.map(({match,...t})=>t),record:detail=>{if(!detail||typeof detail.query!=='string')return;signals.push({text:[detail.query,detail.title||''].join(' '),count:1});signals=signals.slice(-200);},scan});
window.addEventListener('codephi:interest',e=>window.CodePhiPersonalSkills.record(e.detail));
identityLoad();async function identityLoad(){try{activeToken=identity().token;scope=await keyFor(activeToken);const saved=JSON.parse(localStorage.getItem(scope)||'null');if(saved){profile=saved;render();}if(!saved||Date.now()-Number(saved.updatedAt)>86400000)scan();}catch{}}
})();
