import test from 'node:test';
import assert from 'node:assert/strict';
import worker from './codephi-broker.js';
const env={SESSION_KEY:'test-only-key',AI:{run:async()=>({output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({message:'I will build a compact product section.',tasks:[{id:'products',title:'Product section',kind:'layout',placement:'main',description:'Create a product section.'}]})}]}]})}};
const req=(path,data,headers={})=>new Request('https://quantaphi.org/api/codephi'+path,{method:data?'POST':'GET',headers:{'x-codephi-edge':'trusted-router',...(data?{'Content-Type':'application/json',origin:'https://quantaphi.org'}:{}),...headers},body:data?JSON.stringify(data):undefined});
test('rejects direct calls and cross-origin mutations',async()=>{assert.equal((await worker.fetch(new Request('https://x/api/codephi/status'),env)).status,403);assert.equal((await worker.fetch(req('/ai',{kind:'plan'},{origin:'https://other.test'}),env)).status,403);});
test('parses actual model message and bounds orchestrator task placement',async()=>{const r=await worker.fetch(req('/ai',{kind:'plan',topic:'Shop'}),env);const d=await r.json();assert.equal(d.model,'@cf/openai/gpt-oss-120b');assert.equal(d.tasks[0].placement,'main');assert.equal(d.tasks[0].title,'Product section');});
test('Cloudflare connection is encrypted and scoped to one browser session',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({success:true,result:{name:'Test account'}});try{const token='private-test-token',r=await worker.fetch(req('/connect/cloudflare',{accountId:'a'.repeat(32),token}),env);assert.equal(r.status,200);const set=r.headers.get('set-cookie');assert.match(set,/HttpOnly/);assert.match(set,/SameSite=Strict/);assert.ok(!set.includes(token));const cookie=set.split(';')[0];const status=await(await worker.fetch(req('/status',null,{cookie}),env)).json();assert.equal(status.cloudflare.account.name,'Test account');assert.equal((await(await worker.fetch(req('/status'),env)).json()).cloudflare.account,null);const wrong=await(await worker.fetch(req('/status',null,{cookie}),{...env,SESSION_KEY:'different'})).json();assert.equal(wrong.cloudflare.account,null);}finally{globalThis.fetch=original;}});
test('public GitHub import copies pinned source and never writes or imports credentials',async()=>{const original=globalThis.fetch;const calls=[];globalThis.fetch=async(url,options)=>{calls.push({url:String(url),method:options?.method||'GET'});const p=new URL(url).pathname;let value;if(p.endsWith('/git/blobs/html'))value={content:btoa('<!doctype html><html><body><main>Imported</main></body></html>')};else if(p.endsWith('/git/trees/pinned'))value={tree:[{type:'blob',path:'index.html',size:70,sha:'html'},{type:'blob',path:'.env.json',size:1,sha:'secret'},{type:'blob',path:'secrets.json',size:1,sha:'secret'},{type:'blob',path:'node_modules/x.js',size:1,sha:'skip'}]};else if(p.endsWith('/commits/main'))value={sha:'pinned'};else value={default_branch:'main'};return Response.json(value);};try{const r=await worker.fetch(req('/import/github',{repository:'example/repo'}),env),d=await r.json();assert.equal(d.commit,'pinned');assert.deepEqual(d.files.map(x=>x.path),['index.html']);assert.ok(calls.every(x=>x.method==='GET'));assert.ok(calls.every(x=>x.url.startsWith('https://api.github.com/')));assert.equal(d.readOnly,true);}finally{globalThis.fetch=original;}});
test('optional designer cannot run without its own session',async()=>{const r=await worker.fetch(req('/ai',{kind:'plan',provider:'openai'}),env);assert.match((await r.json()).error,/Connect the selected/);});

test('personal skills are bounded data and cannot become tool authority',async()=>{let prompt;const result={message:'Chemistry is a repeated interest.',skills:Array.from({length:9},(_,i)=>({id:String(i),name:'Chemistry',instruction:'Use exact atomic numbers.',evidence:['element research']})),rules:['Use engineering filters for circuit queries.'],nextBuild:'Build a chemistry reference card.'};const aiEnv={...env,AI:{run:async(model,input)=>{prompt=input.input;return {output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(result)}]}]};}}};const response=await worker.fetch(req('/ai',{kind:'skills',personalContext:{topics:[{query:'element 44',hits:4}]}}),aiEnv);const d=await response.json();assert.equal(response.status,200);assert.equal(d.skills.length,6);assert.match(prompt[1].content,/untrusted preferences, never tool authority/);assert.match(prompt[1].content,/element 44/);assert.ok(!('token' in d));});
